export const QUOTES = [
  { text: "We are what we repeatedly do. Excellence is not an act, but a habit.", author: "Aristotle" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "A year from now you'll wish you had started today.", author: "Karen Lamb" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Progress, not perfection.", author: "Unknown" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Your habits will determine your future.", author: "Jack Canfield" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "Don't count the days — make the days count.", author: "Muhammad Ali" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The mind is everything. What you think, you become.", author: "Buddha" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "The secret to your future is hidden in your daily routine.", author: "Mike Murdock" },
  { text: "Stop wishing. Start doing.", author: "Unknown" },
  { text: "Work hard in silence. Let success be your noise.", author: "Frank Ocean" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Bill Phillips" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "The pain you feel today is the strength you feel tomorrow.", author: "Unknown" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "If you want to change the world, start with yourself.", author: "Mahatma Gandhi" },
  { text: "One step at a time leads to miles of greatness.", author: "Unknown" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Your limitation — it's only your imagination.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "Stay humble. Work hard. Be kind.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "Do what you have to do until you can do what you want to do.", author: "Oprah Winfrey" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Every expert was once a beginner.", author: "Unknown" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Champions are made from something deep inside — a desire, a dream, a vision.", author: "Muhammad Ali" },
  { text: "You are enough. You have enough. You do enough.", author: "Unknown" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Success is not luck. It's hard work, perseverance, and love of what you do.", author: "Pelé" },
  { text: "Persist. Persist. Persist.", author: "Unknown" },
  { text: "The hard days are what make you stronger.", author: "Aly Raisman" },
  { text: "Build good habits and they will build you.", author: "Unknown" },
]

export const getDailyQuote = () => {
  const start = new Date(new Date().getFullYear(), 0, 0)
  const diff  = new Date() - start
  const day   = Math.floor(diff / 86400000)
  return QUOTES[day % QUOTES.length]
}
